return {
  cmd = "",
  "ellisonleao/gruvbox.nvim",
  opts = {
    terminal_colors = true, -- add neovim terminal colors
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
      strings = true,
      emphasis = true,
      comments = true,
      operators = false,
      folds = true,
    },
    strikethrough = true,
    invert_selection = true,
    invert_signs = false,
    invert_tabline = false,
    invert_intend_guides = true,
    inverse = true, -- invert background for search, diffs, statuslines and errors
    contrast = "",  -- can be "hard", "soft" or empty string
    palette_overrides = {},
    dim_inactive = false,
    transparent_mode = true,
    inverted_selection = true,
    overrides = {
      Normal = { bg = "#232323" },
      VertSplit = { bg = "#000000" },
      SignColumn = { bg = "#111111" },
      Define = { link = "GruvboxPurple" },
      Macro = { link = "GruvboxPurple" },
      ["@constant.builtin"] = { link = "GruvboxPurple" },
      ["@storageclass.lifetime"] = { link = "GruvboxAqua" },
      ["@text.note"] = { link = "TODO" },
      LspCodeLens = { fg = "#878787" },
      ContextVt = { fg = "#878787" },
      Comment = { fg = "#6c7086", italic = true },
      Folded = { italic = true, fg = "#fe8019", bg = "#3c3836" },
      FoldColumn = { fg = "#fe8019", bg = "#0E1018" },
      DiffAdd = { bold = true, reverse = false, fg = "", bg = "#2a4333" },
      DiffChange = { bold = true, reverse = false, fg = "", bg = "#333841" },
      DiffDelete = { bold = true, reverse = false, fg = "#442d30", bg = "#442d30" },
      DiffText = { bold = true, reverse = false, fg = "", bg = "#213352" },
      StatusLine = { bg = "#ffffff", fg = "#000000" },
      StatusLineNC = { bg = "#3c3836", fg = "#000000" },
      CursorLineNr = { fg = "#8087a2", bg = "#000000" },
      DiagnosticVirtualTextWarn = { fg = "#dfaf87" },
      GruvboxOrangeSign = { fg = "#dfaf87", bg = "#000000" },
      GruvboxAquaSign = { fg = "#8EC07C", bg = "#000000" },
      GruvboxGreenSign = { fg = "#b8bb26", bg = "#000000" },
      GruvboxRedSign = { fg = "#fb4934", bg = "#000000" },
      GruvboxBlueSign = { fg = "#83a598", bg = "#000000" },
      WilderMenu = { fg = "#24273a", bg = "#000000" },
      WilderAccent = { fg = "#f4468f", bg = "#000000" },
    },
  },
}
